version: "3.8"
networks:
  demo-net:
services:
  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    networks:
    - demo-net
    working_dir: /home/$USER/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
    - $PWD/work:/home/$USER/work

